import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '../components/ui/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={'h-full w-full dark:bg-gray-950 ' + inter.className}>
        <Navbar />
        <div className="m-auto max-w-7xl">{children}</div>
      </body>
    </html>
  );
}
