import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '../components/ui/Navbar/Navbar';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={
          'h-full w-full dark:bg-gray-950 flex flex-col items-center ' +
          inter.className
        }
      >
        <Providers>
          <Navbar />
          <main className="w-full xl:w-[1280px] mt-24 py-4 px-6 xl:p-32">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
